Repository scrabill/how-many-days-until-halloween, pull requests merged in 2018-10, with the labels that each got.

#154 Deleted : file and fixed some typos
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: clarification

#166 Use Moment.js library for calculation
  .eslintrc.js
  README.md
  css/styles.css
  index.html
  js/script.js
Labels: clarification, discussion, enhancement

#170 Added random Halloween facts and adjusted styles
  css/styles.css
  index.html
  js/script.js
Labels: Hacktoberfest, clarification, enhancement

#176 Update README.md with Sheilds
  README.md
Labels: clarification, enhancement

#192 Fixed the broken link
  CONTRIBUTING.md
Labels: working on it

#196 Commit and Contributor shield additions to README.md
  README.md
Labels: working on it

#173 Add illustration
  css/styles.css
  index.html
Labels: bug, clarification, working on it

#195 Adds banner to the README
  README.md
  img/readme-banner.jpg
Labels: clarification, working on it

#204 appended digital ocenan's how to raise pull request link for user help
  CONTRIBUTING.md
Labels: clarification

#224 Removed Extra space
  js/script.js
Labels: working on it

#189 Updated mobile styles to fill page.
  css/styles.css
Labels: working on it

#184 added spooky ghost
  css/styles.css
  images/ghost.png
  index.html
Labels: working on it

#193 Features Requested in Issues section.
  ISSUE_TEMPLATE.md
  css/styles.css
Labels: working on it

#197 Add jack-o-lantern emoji
  js/script.js
Labels: working on it

#203 Add pumpkin favicon
  img/favicon.ico
  index.html
Labels: working on it

#262 Pumpkin halloween fact
  js/script.js
Labels: clarification, working on it
